# This publishing topics is to launch all components for x2 gen2 except for localization
publish:
  # CAN
  - /j6/fintekcan0/from_can_bus
  - /j6/peakcan0/from_can_bus
  - /j6/peakcan1/from_can_bus
  - /j6/from_can_bus
  - /gsm8/from_can_bus
  - /pacmod/from_can_bus
  - /pacmod/can_rx
  - /can_rx
  # VEHICLE
  - /vehicle/status/steering_status
  - /vehicle/status/velocity_status
  - /vehicle/status/turn_indicators_status
  - /vehicle/status/control_mode
  - /vehicle/status/gear_status
  - /vehicle/status/wheel_speed_status
  # LIDAR
  - /sensing/lidar/front_upper/pandar_packets
  - /sensing/lidar/front_lower/pandar_packets
  - /sensing/lidar/left_upper/pandar_packets
  - /sensing/lidar/left_lower/pandar_packets
  - /sensing/lidar/right_upper/pandar_packets
  - /sensing/lidar/right_lower/pandar_packets
  - /sensing/lidar/rear_upper/pandar_packets
  - /sensing/lidar/rear_lower/pandar_packets

  # LOCALIZATION Outputs
  - /localization/acceleration
  - /localization/kinematic_state
  - /tf

  # FOR PERCEPTION
  # camera
  # - /sensing/camera/camera0/image_raw/compressed
  # - /sensing/camera/camera1/image_raw/compressed
  # - /sensing/camera/camera2/image_raw/compressed
  # - /sensing/camera/camera3/image_raw/compressed
  # - /sensing/camera/camera4/image_raw/compressed
  # - /sensing/camera/camera5/image_raw/compressed
  # - /sensing/camera/camera6/image_raw/compressed
  # - /sensing/camera/camera7/image_raw/compressed
  # - /sensing/camera/camera8/image_raw/compressed
  # - /sensing/camera/camera9/image_raw/compressed
  # - /sensing/camera/camera10/image_raw/compressed
  - /sensing/camera/camera0/camera_info
  - /sensing/camera/camera1/camera_info
  - /sensing/camera/camera2/camera_info
  - /sensing/camera/camera3/camera_info
  - /sensing/camera/camera4/camera_info
  - /sensing/camera/camera5/camera_info
  - /sensing/camera/camera6/camera_info
  - /sensing/camera/camera7/camera_info
  - /sensing/camera/camera8/camera_info
  - /sensing/camera/camera9/camera_info
  - /sensing/camera/camera10/camera_info
  # camera outputs (NOTE: publishing YOLOX and TLR outputs directly because we currently off them in DLR tests)
  - /perception/object_recognition/detection/rois0
  - /perception/object_recognition/detection/rois1
  - /perception/object_recognition/detection/rois2
  - /perception/object_recognition/detection/rois3
  - /perception/object_recognition/detection/rois4
  - /perception/object_recognition/detection/rois5
  - /perception/traffic_light_recognition/traffic_signals
  # radar
  - /sensing/radar/front_center/nebula_packets
  - /sensing/radar/front_left/nebula_packets
  - /sensing/radar/front_right/nebula_packets
  - /sensing/radar/rear_center/nebula_packets
  - /sensing/radar/rear_left/nebula_packets
  - /sensing/radar/rear_right/nebula_packets

  # FOR PLANNING
  # planning inputs
  - /planning/mission_planning/route
  - /planning/mission_planning/state
  - /planning/scenario_planning/max_velocity_default
  # system / mrm
  - /system/hazard_lights_cmd
  - /system/emergency/control_cmd
  - /system/emergency/gear_cmd
  - /system/emergency/hazard_lights_cmd
  - /system/emergency/turn_indicators_cmd
  - /system/fail_safe/mrm_state
  # `/control/external_cmd_selector` outputs
  - /control/external_cmd_selector/current_selector_mode
  - /external/selected/gear_cmd
  - /external/selected/hazard_lights_cmd
  - /external/selected/heartbeat
  - /external/selected/pedals_cmd
  - /external/selected/steering_cmd
  - /external/selected/turn_indicators_cmd
  # other
  - /autoware/state
  - /awapi/tmp/virtual_traffic_light_states
  - /api/operation_mode/state
