# This publishing topics is to launch autonomous_emergency_braking only
publish:
  - /autoware/state
  - /control/trajectory_follower/lateral/predicted_trajectory
  - /perception/object_recognition/objects
  - /perception/obstacle_segmentation/pointcloud
  - /sensing/imu/imu_data
  - /vehicle/status/velocity_status
  - /tf
