# This publishing topics is to launch control_validator only
publish:
  - /api/operation_mode/state
  - /control/command/control_cmd
  - /control/trajectory_follower/lateral/predicted_trajectory
  - /localization/acceleration
  - /localization/kinematic_state
  - /planning/trajectory
