/diagnostics:
  reliability: best_effort
  history: keep_last
  depth: 100
  durability: volatile
/tf_static:
  reliability: reliable
  history: keep_last
  depth: 1
  durability: transient_local
/perception/obstacle_segmentation/pointcloud:
  reliability: best_effort
  history: keep_last
  depth: 10
  durability: volatile
/perception/obstacle_segmentation/single_frame/pointcloud:
  reliability: best_effort
  history: keep_last
  depth: 10
  durability: volatile
/localization/util/downsample/pointcloud:
  reliability: best_effort
  history: keep_last
  depth: 10
  durability: volatile
/sensing/lidar/concatenated/pointcloud:
  reliability: best_effort
  history: keep_last
  depth: 10
  durability: volatile
/planning/mission_planning/route:
  reliability: reliable
  history: keep_last
  depth: 1
  durability: transient_local
